### PR TITLE
adding gin-gonic template

### PR DESCRIPTION
**Pull request by rajeshdeshpande02**
Adding gin-gonic template for web service application type

### CODE REVIEW

**Review by shubham-asati — COMMENTED** [review]
remove go.sum

**Comment by rajeshdeshpande02** [comment]
@shubham-asati Deleted go.sum file

**Comment by shubham-asati** [comment]
@rajeshdeshpande02  web-services should comply with new codebase.

**Comment by shubham-asati** [comment]
@rajeshdeshpande02 take a look on #4 pull request . Before merging this

**Comment by shubham-asati** [comment]
closing this request as template is already merged

**Pull request closed without merging**
